import { useEffect, useState } from 'react'
import { subscribeLogs, subscribeTickets } from '../services.js'
import { DEFAULT_WORKFLOW_RULES } from '../workflow.js'
import { STATUS_LABELS } from '../config.js'
import TicketDetail, { TicketLink } from '../components/TicketDetail.jsx'

export default function Admin() { const [tickets, setTickets] = useState([]); const [logs, setLogs] = useState([]); const [selected, setSelected] = useState(null); const [tab, setTab] = useState('overview'); useEffect(() => subscribeTickets(setTickets), []); useEffect(() => subscribeLogs(setLogs), []); const counts = { Total: tickets.length, Inbound: tickets.filter(ticket => ticket.ticketType === 'inbound').length, Outbound: tickets.filter(ticket => ticket.ticketType === 'outbound').length, 'In transit': tickets.filter(ticket => ticket.currentStatus === 'in_transit').length, Closed: tickets.filter(ticket => ticket.currentStatus === 'closed').length }; const byStatus = Object.entries(STATUS_LABELS).map(([status, label]) => [label, tickets.filter(ticket => ticket.currentStatus === status).length]); const byDepartment = ['crm', 'warehouse', 'pdi', 'logistics'].map(module => [module, logs.filter(log => log.module === module).length]); const ticketForLog = id => tickets.find(ticket => ticket.id === id)
  return <section className="page"><div className="eyebrow">ADMIN CONTROL CENTER</div><h1>System Administration</h1><p className="muted">Master access to live operations, workflows, history and analytics.</p><div className="tabs"><button className={tab === 'overview' ? 'tab active' : 'tab'} onClick={() => setTab('overview')}>Operations Overview</button><button className={tab === 'analytics' ? 'tab active' : 'tab'} onClick={() => setTab('analytics')}>Analytics</button><button className={tab === 'logs' ? 'tab active' : 'tab'} onClick={() => setTab('logs')}>System Logs</button></div>
    {tab === 'overview' && <><div className="kpi-grid">{Object.entries(counts).map(([key, entry]) => <div className="kpi" key={key}><small>{key}</small><strong>{entry}</strong></div>)}</div><div className="card"><h2>Tickets Flow Manager</h2><div className="table-wrap"><table><thead><tr><th>Rule</th><th>Condition</th><th>Workflow</th><th>Enabled</th></tr></thead><tbody>{DEFAULT_WORKFLOW_RULES.map(rule => <tr key={rule.id}><td className="strong">{rule.name}</td><td>{rule.conditions.sources?.join(', ') || rule.conditions.ticketType} {rule.conditions.destinationCompany ? `→ ${rule.conditions.destinationCompany}` : ''}</td><td>{rule.steps.join(' → ')}</td><td>{rule.enabled ? 'Yes' : 'No'}</td></tr>)}</tbody></table></div></div><div className="card"><h2>Administration Modules</h2><div className="admin-grid"><div><strong>User Management</strong><p className="muted">Operational account administration.</p></div><div><strong>Access Control</strong><p className="muted">Admin retains access to every module.</p></div><div><strong>Flow Manager</strong><p className="muted">Current workflow rule visibility.</p></div><div><strong>System Logs</strong><p className="muted">Immutable ticket activity audit.</p></div></div></div></>}
    {tab === 'analytics' && <><div className="kpi-grid">{byStatus.map(([key, entry]) => <div className="kpi" key={key}><small>{key}</small><strong>{entry}</strong></div>)}</div><div className="card"><h2>Department activity</h2><div className="analytics-list">{byDepartment.map(([module, count]) => <div key={module}><strong>{module.toUpperCase()}</strong><span>{count} logged actions</span></div>)}</div><p className="muted">Live counts are derived from ticket status and immutable activity records.</p></div></>}
    {tab === 'logs' && <div className="card"><h2>Live System Logs</h2><div className="table-wrap"><table><thead><tr><th>Time</th><th>User</th><th>Role</th><th>Action</th><th>Ticket</th><th>Transition</th><th>Details</th></tr></thead><tbody>{logs.map(log => { const ticket = ticketForLog(log.ticketId); return <tr key={log.id}><td>{log.createdAt?.toDate ? log.createdAt.toDate().toLocaleString() : 'Awaiting server timestamp'}</td><td>{log.userName || '—'}</td><td>{log.role || '—'}</td><td>{log.action}</td><td>{ticket ? <TicketLink ticket={ticket} onOpen={setSelected} /> : log.ticketId || '—'}</td><td>{log.previousStatus || 'Start'} → {log.newStatus || '—'}</td><td>{log.details || '—'}</td></tr> })}</tbody></table></div></div>}
    <TicketDetail ticket={selected} onClose={() => setSelected(null)} />
  </section> }
