import { useEffect, useMemo, useState } from 'react'
import { STATUS_LABELS, STATUSES } from '../config.js'
import { subscribeLogs, subscribeTickets } from '../services.js'
import TicketDetail, { TicketLink } from '../components/TicketDetail.jsx'
import './aging-window.css'

const DAY=86400000
const tv=v=>v?.toMillis?v.toMillis():v?new Date(v).getTime():0
const dateOnly=v=>{const ms=tv(v);return ms?new Date(ms).toLocaleDateString('en-IN'): '—'}
const duration=ms=>{if(!ms||ms<0)return'0d';const d=ms/DAY;if(d<1)return`${Math.max(1,Math.round(d*24))}h`;return`${Math.floor(d)}d ${Math.floor((d%1)*24)}h`}
const monthKey=v=>{const ms=tv(v);if(!ms)return'';const d=new Date(ms);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const monthLabel=v=>{if(!v)return'All Months';const[y,m]=v.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-IN',{month:'long',year:'numeric'})}
const transitionsFor=(ticket,logs)=>logs.filter(l=>l.ticketId===ticket.id).sort((a,b)=>tv(a.createdAt)-tv(b.createdAt))
function statusAging(ticket,logs,now){const events=transitionsFor(ticket,logs);const points=[];const created=tv(ticket.createdAt);if(created)points.push({at:created,status:'start'});events.forEach(l=>{const at=tv(l.createdAt);if(at)points.push({at,status:l.newStatus||l.previousStatus||''})});if(!points.length)return{};const totals={warehouse:0,pdi:0,logistics:0,crm:0,other:0};const moduleOf=status=>{if(status===STATUSES.PENDING_WAREHOUSE||status===STATUSES.READY_FOR_DISPATCH)return'warehouse';if(status===STATUSES.READY_FOR_PDI)return'pdi';if(status===STATUSES.LOGISTICS_PENDING||status===STATUSES.IN_TRANSIT)return'logistics';if(status===STATUSES.FORWARD_ORDER_PENDING)return'crm';return'other'};for(let i=0;i<points.length;i++){const start=points[i];const end=points[i+1]?.at||now;if(end>start.at)totals[moduleOf(start.status)]+=end-start.at}return totals}
function prdEta(ticket){const prd=tv(ticket.prdDate);const eta=tv(ticket.logistics?.etaDate||ticket.logistics?.expectedEtaDate||ticket.etaDate);return prd&&eta?eta-prd:null}

export default function AgingWindow(){const[tickets,setTickets]=useState([]);const[logs,setLogs]=useState([]);const[month,setMonth]=useState('');const[search,setSearch]=useState('');const[status,setStatus]=useState('all');const[detail,setDetail]=useState(null);const[now]=useState(()=>Date.now());useEffect(()=>subscribeTickets(setTickets),[]);useEffect(()=>subscribeLogs(setLogs),[])
 const monthOptions=useMemo(()=>[...new Set(tickets.map(t=>monthKey(t.ticketAssignedDate||t.createdAt)).filter(Boolean))].sort().reverse(),[tickets])
 const rows=useMemo(()=>tickets.map(ticket=>{const aging=statusAging(ticket,logs,now);const assigned=tv(ticket.ticketAssignedDate)||tv(ticket.createdAt);const closed=tv(ticket.currentStatus===STATUSES.CLOSED?(ticket.updatedAt||ticket.closedAt):null);const assignedToClosed=assigned?(closed?closed:now)-assigned:null;const prd=tv(ticket.prdDate);const eta=ticket.logistics?.etaDate||ticket.logistics?.expectedEtaDate||ticket.etaDate;const etaMs=tv(eta);return{ticket,aging,assignedToClosed,overall:Math.max(0,now-tv(ticket.createdAt)),prdEta:prdEta(ticket),prd,eta,etaMs}}).filter(row=>{if(month&&monthKey(row.ticket.ticketAssignedDate||row.ticket.createdAt)!==month)return false;if(status!=='all'&&row.ticket.currentStatus!==status)return false;const hay=[row.ticket.ticketId,row.ticket.customerName,row.ticket.destinationBranch,row.ticket.itemCode,row.ticket.shed].join(' ').toLowerCase();return !search||hay.includes(search.toLowerCase())}),[tickets,logs,month,status,search,now])
 const stats=useMemo(()=>{const avg=key=>rows.length?rows.reduce((s,r)=>s+(r[key]||0),0)/rows.length:0;const etaRows=rows.filter(r=>r.prdEta!==null);const avgEta=etaRows.length?etaRows.reduce((s,r)=>s+r.prdEta,0)/etaRows.length:0;const active=rows.filter(r=>r.ticket.currentStatus!==STATUSES.CLOSED);const buckets={under2:active.filter(r=>r.overall<2*DAY).length,twoTo5:active.filter(r=>r.overall>=2*DAY&&r.overall<5*DAY).length,fiveTo10:active.filter(r=>r.overall>=5*DAY&&r.overall<10*DAY).length,over10:active.filter(r=>r.overall>=10*DAY).length};return{avgAssigned:avg('assignedToClosed'),avgOverall:avg('overall'),avgWarehouse:avg(r=>r.aging.warehouse),avgPdi:avg(r=>r.aging.pdi),avgLogistics:avg(r=>r.aging.logistics),avgEta,buckets,active:active.length,closed:rows.length-active.length}} , [rows])
 return <section className="card aging-window"><div className="aging-hero"><div><span className="section-kicker">AGING & SLA INTELLIGENCE</span><h2>Ticket Aging Window</h2><p className="muted">Measure PRD-to-ETA, assigned-to-closed and time spent across Warehouse, PDI and Logistics for every ticket.</p></div><div className="aging-filter-row"><label>MONTH<select value={month} onChange={e=>setMonth(e.target.value)}><option value="">All Months</option>{monthOptions.map(m=><option key={m}>{monthLabel(m)}</option>)}</select></label><label>STATUS<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Statuses</option>{Object.entries(STATUS_LABELS).map(([k,v])=><option key={k}>{v}</option>)}</select></label><label className="aging-search">SEARCH<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ticket, customer, branch, item…"/></label></div></div>
 <div className="aging-kpis"><div><small>Tickets in scope</small><strong>{rows.length}</strong><span>{stats.active} active · {stats.closed} closed</span></div><div><small>Assigned → Closed</small><strong>{duration(stats.avgAssigned)}</strong><span>average lifecycle</span></div><div><small>Warehouse Aging</small><strong>{duration(stats.avgWarehouse)}</strong><span>average time in warehouse</span></div><div><small>PDI Aging</small><strong>{duration(stats.avgPdi)}</strong><span>average time in PDI</span></div><div><small>Logistics Aging</small><strong>{duration(stats.avgLogistics)}</strong><span>average time in logistics</span></div><div><small>PRD → ETA</small><strong>{duration(stats.avgEta)}</strong><span>average planning gap</span></div></div>
 <div className="aging-insight-grid"><div className="aging-panel"><div className="aging-panel-head"><div><span className="section-kicker">ACTIVE AGE DISTRIBUTION</span><h3>How old are active tickets?</h3></div></div>{[['under2','Under 2 days'],['twoTo5','2–5 days'],['fiveTo10','5–10 days'],['over10','10+ days']].map(([key,label])=><div className="aging-bar-row" key={key}><span>{label}</span><strong>{stats.buckets[key]}</strong><i><b style={{width:`${rows.length?stats.buckets[key]/Math.max(1,stats.active)*100:0}%`}}/></i></div>)}</div><div className="aging-panel"><span className="section-kicker">ANALYSIS</span><h3>Operational aging signals</h3><div className="aging-signal"><span>Oldest active ticket</span><strong>{rows.filter(r=>r.ticket.currentStatus!==STATUSES.CLOSED).sort((a,b)=>b.overall-a.overall)[0]?.ticket.ticketId||'—'}</strong></div><div className="aging-signal"><span>Longest warehouse exposure</span><strong>{duration(Math.max(0,...rows.map(r=>r.aging.warehouse)))}</strong></div><div className="aging-signal"><span>Longest PDI exposure</span><strong>{duration(Math.max(0,...rows.map(r=>r.aging.pdi)))}</strong></div><div className="aging-signal"><span>Longest logistics exposure</span><strong>{duration(Math.max(0,...rows.map(r=>r.aging.logistics)))}</strong></div></div></div>
 <div className="aging-table-head"><div><span className="section-kicker">TICKET-LEVEL AGING</span><h3>Detailed Aging Register</h3></div><span>{rows.length} records</span></div><div className="table-wrap aging-table"><table><thead><tr><th>Ticket</th><th>Assigned</th><th>PRD</th><th>ETA</th><th>Assigned → Closed</th><th>Warehouse</th><th>PDI</th><th>Logistics</th><th>Overall</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.ticket.id}><td><TicketLink ticket={row.ticket} onOpen={setDetail}/></td><td>{dateOnly(row.ticket.ticketAssignedDate||row.ticket.createdAt)}</td><td>{row.ticket.prdDate||'—'}</td><td>{row.eta||'—'}</td><td>{duration(row.assignedToClosed)}</td><td>{duration(row.aging.warehouse)}</td><td>{duration(row.aging.pdi)}</td><td>{duration(row.aging.logistics)}</td><td className="strong">{duration(row.overall)}</td><td><span className="aging-status">{STATUS_LABELS[row.ticket.currentStatus]||row.ticket.currentStatus}</span></td></tr>))}</tbody></table></div><TicketDetail ticket={detail} onClose={()=>setDetail(null)}/></section>
}
