import { useEffect, useMemo, useState } from 'react'
import { STATUS_LABELS, STATUSES } from '../config.js'
import { subscribeLogs, subscribeTickets } from '../services.js'
import TicketDetail, { TicketLink } from '../components/TicketDetail.jsx'
import './aging-window.css'

const DAY=86400000
const HOUR=3600000
const MINUTE=60000
const tv=v=>v?.toMillis?v.toMillis():v?new Date(v).getTime():0
const dateOnly=v=>{const ms=tv(v);return ms?new Date(ms).toLocaleDateString('en-IN'):'—'}
const duration=ms=>{if(ms===null||ms===undefined||Number.isNaN(ms)||ms<=0)return'0m';let totalMinutes=Math.round(ms/MINUTE);if(totalMinutes<60)return`${totalMinutes}m`;const hours=Math.floor(totalMinutes/60);const minutes=totalMinutes%60;if(hours<24)return minutes?`${hours}h ${minutes}m`:`${hours}h`;const days=Math.floor(hours/24);const remHours=hours%24;return remHours?`${days}d ${remHours}h`:`${days}d`}
const monthKey=v=>{const ms=tv(v);if(!ms)return'';const d=new Date(ms);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const monthLabel=v=>{if(!v)return'All Months';const[y,m]=v.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-IN',{month:'long',year:'numeric'})}
const transitionsFor=(ticket,logs)=>logs.filter(l=>l.ticketId===ticket.id&&tv(l.createdAt)).sort((a,b)=>tv(a.createdAt)-tv(b.createdAt))
const moduleOfStatus=status=>{if(status===STATUSES.PENDING_WAREHOUSE||status===STATUSES.READY_FOR_DISPATCH)return'warehouse';if(status===STATUSES.READY_FOR_PDI)return'pdi';if(status===STATUSES.LOGISTICS_PENDING||status===STATUSES.IN_TRANSIT)return'logistics';if(status===STATUSES.FORWARD_ORDER_PENDING)return'crm';return'other'}
function statusAging(ticket,logs,now){const events=transitionsFor(ticket,logs);const points=[];const created=tv(ticket.createdAt);if(created)points.push({at:created,status:'start'});events.forEach(l=>{const at=tv(l.createdAt);const next=l.newStatus;if(at&&next&&next!==l.previousStatus)points.push({at,status:next})});const totals={warehouse:0,pdi:0,logistics:0,crm:0,other:0};if(!points.length)return totals;for(let i=0;i<points.length;i++){const start=points[i];const end=points[i+1]?.at||now;if(end>start.at)totals[moduleOfStatus(start.status)]+=end-start.at}return totals}
const prdEta=ticket=>{const prd=tv(ticket.prdDate);const eta=tv(ticket.logistics?.etaDate||ticket.logistics?.expectedEtaDate||ticket.etaDate);return prd&&eta?eta-prd:null}
const ageBucket=ms=>{if(ms<2*DAY)return'under2';if(ms<5*DAY)return'twoTo5';if(ms<10*DAY)return'fiveTo10';return'over10'}
const eventDuration=(logs,actions)=>{const selected=logs.filter(l=>actions.includes(l.action)).sort((a,b)=>tv(a.createdAt)-tv(b.createdAt));if(selected.length<2)return 0;return Math.max(0,tv(selected[selected.length-1].createdAt)-tv(selected[0].createdAt))}

export default function AgingWindow(){
 const[tickets,setTickets]=useState([]);const[logs,setLogs]=useState([]);const[month,setMonth]=useState('');const[search,setSearch]=useState('');const[status,setStatus]=useState('all');const[stage,setStage]=useState('all');const[bucket,setBucket]=useState('all');const[detail,setDetail]=useState(null);const[now]=useState(()=>Date.now())
 useEffect(()=>subscribeTickets(setTickets),[]);useEffect(()=>subscribeLogs(setLogs),[])
 const monthOptions=useMemo(()=>[...new Set(tickets.map(t=>monthKey(t.ticketAssignedDate||t.createdAt)).filter(Boolean))].sort().reverse(),[tickets])
 const rows=useMemo(()=>tickets.map(ticket=>{const aging=statusAging(ticket,logs,now);const assigned=tv(ticket.ticketAssignedDate)||tv(ticket.createdAt);const closed=ticket.currentStatus===STATUSES.CLOSED?(tv(ticket.closedAt)||tv(ticket.updatedAt)):0;const assignedToClosed=assigned?Math.max(0,(closed||now)-assigned):0;const overall=Math.max(0,now-tv(ticket.createdAt));const currentStage=moduleOfStatus(ticket.currentStatus);const ticketLogs=transitionsFor(ticket,logs);const dispatchLog=ticketLogs.find(l=>l.action==='warehouse_dispatch_completed');const pdiLogs=ticketLogs.filter(l=>l.action==='pdi_inspection_completed');const reinspectionCount=ticketLogs.filter(l=>l.action==='pdi_new_batch_requested').length;const firstDispatch=tv(dispatchLog?.createdAt);const firstPdi=tv(pdiLogs[0]?.createdAt);const dispatchToPdi=firstDispatch&&firstPdi?Math.max(0,firstPdi-firstDispatch):0;const pdiCycle=eventDuration(ticketLogs,['pdi_new_batch_requested','warehouse_batch_provided']);return{ticket,aging,assignedToClosed,overall,prdEta:prdEta(ticket),currentStage,reinspectionCount,dispatchToPdi,pdiCycle}}).filter(row=>{const t=row.ticket;if(month&&monthKey(t.ticketAssignedDate||t.createdAt)!==month)return false;if(status!=='all'&&t.currentStatus!==status)return false;if(stage!=='all'&&row.currentStage!==stage)return false;if(bucket!=='all'&&ageBucket(row.overall)!==bucket)return false;const hay=[t.ticketId,t.customerName,t.destinationBranch,t.itemCode,t.shed,t.source].join(' ').toLowerCase();return!search||hay.includes(search.toLowerCase())}),[tickets,logs,month,status,stage,bucket,search,now])
 const stats=useMemo(()=>{const avg=selector=>rows.length?rows.reduce((sum,row)=>sum+Number(selector(row)||0),0)/rows.length:0;const etaRows=rows.filter(r=>r.prdEta!==null);const avgEta=etaRows.length?etaRows.reduce((sum,r)=>sum+r.prdEta,0)/etaRows.length:0;const active=rows.filter(r=>r.ticket.currentStatus!==STATUSES.CLOSED);const buckets={under2:active.filter(r=>ageBucket(r.overall)==='under2').length,twoTo5:active.filter(r=>ageBucket(r.overall)==='twoTo5').length,fiveTo10:active.filter(r=>ageBucket(r.overall)==='fiveTo10').length,over10:active.filter(r=>ageBucket(r.overall)==='over10').length};const totalReinspections=rows.reduce((s,r)=>s+r.reinspectionCount,0);return{avgAssigned:avg(r=>r.assignedToClosed),avgOverall:avg(r=>r.overall),avgWarehouse:avg(r=>r.aging.warehouse),avgPdi:avg(r=>r.aging.pdi),avgLogistics:avg(r=>r.aging.logistics),avgCrm:avg(r=>r.aging.crm),avgEta,buckets,active:active.length,closed:rows.length-active.length,totalReinspections,avgDispatchToPdi:avg(r=>r.dispatchToPdi),avgPdiCycle:avg(r=>r.pdiCycle)}},[rows])
 const oldest=useMemo(()=>rows.filter(r=>r.ticket.currentStatus!==STATUSES.CLOSED).sort((a,b)=>b.overall-a.overall)[0],[rows])
 return <section className="card aging-window">
   <div className="aging-hero"><div><span className="section-kicker">AGING & SLA INTELLIGENCE</span><h2>Ticket Aging & SLA Intelligence</h2><p className="muted">Lifecycle, stage aging, queue exposure and SLA analysis from the ticket's recorded operational events. Durations preserve minute-level precision and automatically expand to hours and days.</p></div><div className="aging-live"><span/>LIVE DATA · {rows.length} IN SCOPE</div></div>
   <div className="aging-filter-shell"><div className="aging-filter-title"><div><span className="section-kicker">ANALYSIS FILTERS</span><strong>Drill into the operational aging register</strong></div><button className="secondary" onClick={()=>{setMonth('');setStatus('all');setStage('all');setBucket('all');setSearch('')}}>Reset Filters</button></div><div className="aging-filter-row"><label>MONTH<select value={month} onChange={e=>setMonth(e.target.value)}><option value="">All Months</option>{monthOptions.map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select></label><label>STATUS<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Statuses</option>{Object.entries(STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>CURRENT STAGE<select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All Teams</option><option value="crm">CRM</option><option value="warehouse">Warehouse</option><option value="pdi">PDI</option><option value="logistics">Logistics</option></select></label><label>AGE BAND<select value={bucket} onChange={e=>setBucket(e.target.value)}><option value="all">All Age Bands</option><option value="under2">Under 2 days</option><option value="twoTo5">2–5 days</option><option value="fiveTo10">5–10 days</option><option value="over10">10+ days</option></select></label><label className="aging-search">SEARCH<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ticket, customer, branch, item, shed…"/></label></div><div className="filter-result">Showing <strong>{rows.length}</strong> of {tickets.length} tickets · {stats.active} active · {stats.closed} closed · {stats.totalReinspections} reinspection request(s)</div></div>
   <div className="aging-kpis"><div><small>Assigned → Closed</small><strong>{duration(stats.avgAssigned)}</strong><span>average lifecycle</span></div><div><small>Overall Ticket Age</small><strong>{duration(stats.avgOverall)}</strong><span>creation → now / close</span></div><div><small>Warehouse Aging</small><strong>{duration(stats.avgWarehouse)}</strong><span>warehouse exposure</span></div><div><small>PDI Aging</small><strong>{duration(stats.avgPdi)}</strong><span>inspection exposure</span></div><div><small>Logistics Aging</small><strong>{duration(stats.avgLogistics)}</strong><span>logistics exposure</span></div><div><small>PRD → ETA</small><strong>{duration(Math.abs(stats.avgEta))}</strong><span>planning gap</span></div></div>
   <div className="aging-insight-grid"><div className="aging-panel"><div className="aging-panel-head"><div><span className="section-kicker">ACTIVE AGE DISTRIBUTION</span><h3>Where are active tickets aging?</h3></div><span className="aging-panel-count">{stats.active} active</span></div>{[['under2','Under 2 days'],['twoTo5','2–5 days'],['fiveTo10','5–10 days'],['over10','10+ days']].map(([key,label])=><button type="button" className={`aging-bar-row ${bucket===key?'selected':''}`} key={key} onClick={()=>setBucket(bucket===key?'all':key)}><span>{label}</span><strong>{stats.buckets[key]}</strong><i><b style={{width:`${stats.active?stats.buckets[key]/stats.active*100:0}%`}}/></i></button>)}</div><div className="aging-panel"><span className="section-kicker">SLA SIGNALS</span><h3>Operational pressure & bottlenecks</h3><div className="aging-signal"><span>Oldest active ticket</span><strong>{oldest?.ticket.ticketId||'—'}{oldest&&<small>{duration(oldest.overall)}</small>}</strong></div><div className="aging-signal"><span>Longest Warehouse exposure</span><strong>{duration(Math.max(0,...rows.map(r=>r.aging.warehouse)))}</strong></div><div className="aging-signal"><span>Longest PDI exposure</span><strong>{duration(Math.max(0,...rows.map(r=>r.aging.pdi)))}</strong></div><div className="aging-signal"><span>Longest Logistics exposure</span><strong>{duration(Math.max(0,...rows.map(r=>r.aging.logistics)))}</strong></div><div className="aging-signal"><span>CRM / Forward Order exposure</span><strong>{duration(Math.max(0,...rows.map(r=>r.aging.crm)))}</strong></div><div className="aging-signal"><span>Avg Dispatch → PDI</span><strong>{duration(stats.avgDispatchToPdi)}</strong></div><div className="aging-signal"><span>Reinspection requests</span><strong>{stats.totalReinspections}</strong></div></div></div>
   <div className="aging-table-head"><div><span className="section-kicker">TICKET-LEVEL SLA REGISTER</span><h3>Detailed Aging & Lifecycle</h3><p className="muted">Every duration is calculated from recorded timestamps; short processes remain in minutes instead of being rounded up to hours.</p></div><span>{rows.length} records</span></div><div className="table-wrap aging-table"><table><thead><tr><th>Ticket</th><th>Assigned</th><th>PRD</th><th>ETA</th><th>PRD → ETA</th><th>Assigned → Closed</th><th>Warehouse</th><th>PDI</th><th>Logistics</th><th>CRM / Forward</th><th>Reinspect</th><th>Dispatch → PDI</th><th>Overall</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.ticket.id}><td><TicketLink ticket={row.ticket} onOpen={setDetail}/></td><td>{dateOnly(row.ticket.ticketAssignedDate||row.ticket.createdAt)}</td><td>{row.ticket.prdDate||'—'}</td><td>{row.ticket.logistics?.etaDate||row.ticket.logistics?.expectedEtaDate||row.ticket.etaDate||'—'}</td><td>{row.prdEta===null?'—':duration(Math.abs(row.prdEta))}</td><td>{duration(row.assignedToClosed)}</td><td>{duration(row.aging.warehouse)}</td><td>{duration(row.aging.pdi)}</td><td>{duration(row.aging.logistics)}</td><td>{duration(row.aging.crm)}</td><td>{row.reinspectionCount}</td><td>{duration(row.dispatchToPdi)}</td><td className="strong">{duration(row.overall)}</td><td><span className="aging-status">{STATUS_LABELS[row.ticket.currentStatus]||row.ticket.currentStatus}</span></td></tr>):<tr><td colSpan="14"><div className="empty-forward"><strong>No tickets match the selected filters.</strong><span>Reset filters or broaden the search to see the aging register.</span></div></td></tr>}</tbody></table></div><TicketDetail ticket={detail} onClose={()=>setDetail(null)}/>
 </section>
}
