import { useEffect, useMemo, useState } from 'react'
import { DESTINATION_COMPANIES, INBOUND_SOURCES, SHEDS, TICKET_TYPES } from '../config.js'
import { createTicket, subscribeTickets } from '../services.js'
import { useAuth } from '../auth.jsx'

const inboundFields = ['ticketId','customerName','source','destinationCompany','destinationBranch','freightOrderNo','loadNumber','vehicleNumber','shed','itemCode','itemDescription','qty','prdDate']
const outboundFields = ['ticketId','customerName','destinationBranch','warehouseOrderNumber','freightOrderNo','position','shed','itemCode','itemDescription','qty','prdDate']
const labels = { ticketId:'Ticket ID',customerName:'Customer Name',source:'Source',destinationCompany:'Destination Company',destinationBranch:'Destination Branch',freightOrderNo:'Freight Order No.',loadNumber:'Load Number',vehicleNumber:'Vehicle Number',shed:'Shed',itemCode:'Item Code',itemDescription:'Item Description',qty:'Qty',prdDate:'PRD Date',warehouseOrderNumber:'Warehouse Order Number',position:'Position' }
const blank = type => Object.fromEntries((type === TICKET_TYPES.INBOUND ? inboundFields : outboundFields).map(k => [k,'']))

function Field({ name, value, onChange, type }) { if(name==='source') return <label>{labels[name]}<select value={value} onChange={onChange} required><option value="">Select source</option>{INBOUND_SOURCES.map(x=><option key={x}>{x}</option>)}</select></label>; if(name==='destinationCompany') return <label>{labels[name]}<select value={value} onChange={onChange} required><option value="">Select company</option>{DESTINATION_COMPANIES.map(x=><option key={x}>{x}</option>)}</select></label>; if(name==='shed') return <label>{labels[name]}<select value={value} onChange={onChange} required><option value="">Select shed</option>{SHEDS.map(x=><option key={x}>{x}</option>)}</select></label>; return <label>{labels[name]}<input type={name==='qty'?'number':name==='prdDate'?'date':'text'} min={name==='qty'?0:undefined} value={value} onChange={onChange} required /></label> }

export default function CRM() {
 const { profile } = useAuth(); const [type,setType]=useState(TICKET_TYPES.INBOUND); const [form,setForm]=useState(blank(type)); const [tickets,setTickets]=useState([]); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [tab,setTab]=useState('entry')
 useEffect(()=>subscribeTickets(setTickets),[])
 useEffect(()=>setForm(blank(type)),[type])
 const visible=useMemo(()=>tickets,[tickets])
 async function submit(e){e.preventDefault();setSaving(true);setMessage('');try{await createTicket({...form,ticketType:type,source:type===TICKET_TYPES.INBOUND?form.source:undefined,destinationCompany:type===TICKET_TYPES.INBOUND?form.destinationCompany:undefined,qty:Number(form.qty)},profile);setForm(blank(type));setMessage('Ticket created and routed according to the active workflow.')}catch(err){setMessage(err.message)}finally{setSaving(false)}}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">CRM PORTAL</div><h1>Ticket Entry & Live Tracking</h1><p className="muted">Create inbound or outbound tickets and monitor their current workflow state.</p></div></div><div className="tabs"><button className={tab==='entry'?'tab active':'tab'} onClick={()=>setTab('entry')}>Add Ticket / Upload Tickets Dump</button><button className={tab==='log'?'tab active':'tab'} onClick={()=>setTab('log')}>Master Log & Live Tracking</button></div>{tab==='entry'?<><div className="type-switch"><button className={type===TICKET_TYPES.INBOUND?'type active inbound':'type'} onClick={()=>setType(TICKET_TYPES.INBOUND)}>INBOUND TICKET</button><button className={type===TICKET_TYPES.OUTBOUND?'type active outbound':'type'} onClick={()=>setType(TICKET_TYPES.OUTBOUND)}>OUTBOUND TICKET</button></div><div className="card"><div className="card-head"><div><h2>Add {type==='inbound'?'Inbound':'Outbound'} Ticket</h2><p className="muted">Fields change automatically with ticket type.</p></div><span className="badge">{type.toUpperCase()}</span></div><form className="form-grid" onSubmit={submit}>{(type===TICKET_TYPES.INBOUND?inboundFields:outboundFields).map(name=><Field key={name} name={name} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})} type={type}/>)}<div className="form-actions"><button className="primary" disabled={saving}>{saving?'Saving…':'Save & Route Ticket'}</button><button type="button" className="secondary">Upload Tickets Dump</button></div></form>{message&&<div className="notice">{message}</div>}</div></>:<div className="card"><div className="card-head"><h2>Master Log & Live Tracking</h2><span className="muted">{visible.length} tickets</span></div><div className="table-wrap"><table><thead><tr><th>Ticket</th><th>Type</th><th>Customer</th><th>Source / Destination</th><th>Qty</th><th>Module</th><th>Status</th></tr></thead><tbody>{visible.map(t=><tr key={t.id}><td className="strong">{t.ticketId||t.id}</td><td><span className={`badge ${t.ticketType}`}>{t.ticketType}</span></td><td>{t.customerName}</td><td>{t.source||t.destinationBranch||'—'}</td><td>{t.qty}</td><td>{t.currentModule||'—'}</td><td>{t.currentStatus||'—'}</td></tr>)}</tbody></table></div></div>}</section>
}
