import { useMemo, useState } from 'react'
import { STATUS_LABELS, STATUSES } from '../config.js'
import { subscribeLogs, subscribeTickets, updateTicket } from '../services.js'
import { useAuth } from '../auth.jsx'
import TicketDetail, { TicketLink } from '../components/TicketDetail.jsx'
import { useEffect } from 'react'

const tv=v=>v?.toMillis?v.toMillis():v?new Date(v).getTime():0
const fmt=v=>tv(v)?new Date(tv(v)).toLocaleString():'—'
const isNoStock=t=>t?.pdi?.closedReason==='no_stock'

export default function CRMClosedTickets(){
 const{profile}=useAuth();const[tickets,setTickets]=useState([]);const[logs,setLogs]=useState([]);const[selected,setSelected]=useState(null);const[search,setSearch]=useState('');const[kind,setKind]=useState('all');const[saving,setSaving]=useState(null)
 useEffect(()=>subscribeTickets(setTickets),[]);useEffect(()=>subscribeLogs(setLogs),[])
 const rows=useMemo(()=>tickets.filter(t=>t.currentStatus===STATUSES.CLOSED).filter(t=>{const hay=[t.ticketId,t.customerName,t.destinationBranch,t.itemCode,t.shed].join(' ').toLowerCase();if(search&&!hay.includes(search.toLowerCase()))return false;if(kind==='no_stock'&&!isNoStock(t))return false;if(kind==='logistics'&&isNoStock(t))return false;return true}),[tickets,search,kind])
 async function reassign(ticket){if(saving)return;setSaving(ticket.id);try{await updateTicket(ticket.id,{pdi:{...(ticket.pdi||{}),reassignedToOec:true,reassignedToOecAt:new Date(),reassignedToOecBy:profile?.uid||''}},profile,'crm_reassigned_to_oec',{module:'crm',previousStatus:STATUSES.CLOSED,newStatus:STATUSES.CLOSED,details:`CRM marked closed ticket ${ticket.ticketId} as reassigned to OEC team.`,metadata:{reason:'no_stock',ticketId:ticket.ticketId}})}finally{setSaving(null)}}
 return <section className="page"><div className="page-head"><div><div className="eyebrow">CRM PORTAL · CLOSED TICKETS</div><h1>Closed Tickets</h1><p className="muted">View every closed ticket and identify whether it was closed by Logistics or because Warehouse reported no stock and PDI confirmed it.</p></div></div><div className="card"><div className="filter-bar"><input placeholder="Search ticket, customer, branch, item, shed…" value={search} onChange={e=>setSearch(e.target.value)}/><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All Closed Tickets</option><option value="logistics">Closed by Logistics</option><option value="no_stock">Closed Due to No Stock</option></select><button className="secondary" onClick={()=>{setSearch('');setKind('all')}}>Reset</button></div><div className="filter-result">Showing <strong>{rows.length}</strong> closed ticket(s)</div><div className="table-wrap"><table><thead><tr><th>Ticket Number</th><th>Customer</th><th>Item Code</th><th>Destination</th><th>Qty</th><th>Status</th><th>Closed By</th><th>Closed At</th><th>Action</th></tr></thead><tbody>{rows.map(t=>{const noStock=isNoStock(t);const log=logs.filter(l=>l.ticketId===t.id&&l.action==='pdi_no_stock_ticket_closed').sort((a,b)=>tv(b.createdAt)-tv(a.createdAt))[0];const reassigned=!!t.pdi?.reassignedToOec;return <tr key={t.id}><td><TicketLink ticket={t} onOpen={setSelected}/></td><td>{t.customerName||'—'}</td><td>{t.itemCode||'—'}</td><td>{t.destinationBranch||t.destinationCompany||'—'}</td><td>{t.qty||'—'}</td><td><span className="badge">CLOSED</span></td><td><strong>{noStock?'No Stock Available':'Logistics'}</strong><small className="muted" style={{display:'block'}}>{noStock?'Warehouse + PDI confirmation':'ETA + Actual Branch Reporting'}</small></td><td>{fmt(log?.createdAt||t.updatedAt)}</td><td>{noStock?(reassigned?<span className="notice success">Reassigned to OEC</span>:<button className="primary" disabled={saving===t.id} onClick={()=>reassign(t)}>{saving===t.id?'Updating…':'Reassigned to OEC Team'}</button>):<span className="muted">—</span>}</td></tr>})}</tbody></table></div></div><TicketDetail ticket={selected} onClose={()=>setSelected(null)}/></section>
}
