import { useEffect, useMemo, useState } from 'react'
import { STATUS_LABELS, STATUSES } from '../config.js'
import { subscribeLogs, subscribeTickets, updateTicket } from '../services.js'
import { useAuth } from '../auth.jsx'
import { isForwardOrderTicket } from '../workflow.js'
import TicketDetail, { TicketLink } from '../components/TicketDetail.jsx'
import './crm-forward-orders.css'

const tv=value=>value?.toMillis?value.toMillis():value?new Date(value).getTime():0
const fmt=value=>tv(value)?new Date(tv(value)).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'

export default function CRMForwardOrders(){
 const {profile}=useAuth()
 const [tickets,setTickets]=useState([])
 const [logs,setLogs]=useState([])
 const [selected,setSelected]=useState(null)
 const [detail,setDetail]=useState(null)
 const [rpl,setRpl]=useState('')
 const [forwardFo,setForwardFo]=useState('')
 const [remarks,setRemarks]=useState('')
 const [saving,setSaving]=useState(false)
 const [message,setMessage]=useState('')
 useEffect(()=>subscribeTickets(setTickets),[])
 useEffect(()=>subscribeLogs(setLogs),[])
 const pending=useMemo(()=>tickets.filter(ticket=>ticket.currentStatus===STATUSES.FORWARD_ORDER_PENDING&&isForwardOrderTicket(ticket)),[tickets])
 const completed=useMemo(()=>tickets.filter(ticket=>isForwardOrderTicket(ticket)&&ticket.forwardOrder?.rplNumber&&ticket.forwardOrder?.forwardingFoNumber&&ticket.currentStatus!==STATUSES.FORWARD_ORDER_PENDING),[tickets])
 function open(ticket){setSelected(ticket);setRpl(ticket.forwardOrder?.rplNumber||'');setForwardFo(ticket.forwardOrder?.forwardingFoNumber||'');setRemarks(ticket.forwardOrder?.remarks||'');setMessage('')}
 async function submit(event){event.preventDefault();if(!selected||saving)return;const rplNumber=rpl.trim();const forwardingFoNumber=forwardFo.trim();if(!rplNumber||!forwardingFoNumber)return;setSaving(true);setMessage('')
  try{await updateTicket(selected.id,{currentStatus:STATUSES.READY_FOR_DISPATCH,currentModule:'warehouse',previousStatus:selected.currentStatus,forwardOrder:{...(selected.forwardOrder||{}),rplNumber,forwardingFoNumber,remarks:remarks.trim(),completedAt:new Date(),completedBy:profile?.uid||''},forwardingFoNumber},profile,'crm_forward_order_completed',{module:'crm',previousStatus:selected.currentStatus,newStatus:STATUSES.READY_FOR_DISPATCH,details:`Forward order completed for ${selected.ticketId}. RPL Number: ${rplNumber}. Forwarding FO Number: ${forwardingFoNumber}.`,metadata:{rplNumber,forwardingFoNumber,itemCode:selected.itemCode||'',itemDescription:selected.itemDescription||'',remarks:remarks.trim()}});setMessage('Forward order saved successfully. Ticket is now Ready for Dispatch.');setSelected(null)}catch(error){setMessage(error?.message||'Unable to save forward order.')}finally{setSaving(false)}}
 return <section className="page forward-orders-page"><div className="page-head"><div><div className="eyebrow">CRM · FORWARD ORDER DESK</div><h1>Forward Order Tickets</h1><p className="muted">Process eligible inbound 5000 tickets after Warehouse movement and before Dispatch.</p></div><div className="forward-kpis"><div><small>Awaiting CRM</small><strong>{pending.length}</strong></div><div><small>Forwarded</small><strong>{completed.length}</strong></div></div></div>
  <div className="forward-rule-card"><div className="rule-icon">↗</div><div><strong>Automatic routing rule</strong><p>Inbound + Destination Company 5000 + Source Haridwar, Shirwal/Shirval, Khalapur or Supplier → Warehouse Movement → this desk → Dispatch.</p></div><span className="rule-badge">LIVE WORKFLOW</span></div>
  <div className="card"><div className="card-head"><div><span className="section-kicker">ACTION QUEUE</span><h2>Awaiting Forward Order Details</h2><p className="muted">RPL and Forwarding FO are entered by CRM. Item Code and Item Description are read directly from the ticket.</p></div><span className="summary-count">{pending.length} pending</span></div>
   <div className="table-wrap"><table><thead><tr><th>Ticket</th><th>Source</th><th>Customer</th><th>Item Code</th><th>Item Description</th><th>Qty</th><th>Destination</th><th>Status</th><th>Action</th></tr></thead><tbody>{pending.length?pending.map(ticket=><tr key={ticket.id}><td><TicketLink ticket={ticket} onOpen={setDetail}/></td><td><span className="forward-source">{ticket.source||'—'}</span></td><td>{ticket.customerName||'—'}</td><td className="strong">{ticket.itemCode||'—'}</td><td className="description-cell">{ticket.itemDescription||'—'}</td><td>{ticket.qty??'—'}</td><td>{ticket.destinationBranch||ticket.destinationCompany||'—'}</td><td><span className="status-chip">{STATUS_LABELS[ticket.currentStatus]||ticket.currentStatus}</span></td><td><button className="primary" onClick={()=>open(ticket)}>Add RPL & Forwarding FO</button></td></tr>):<tr><td colSpan="9"><div className="empty-forward"><span>✓</span><strong>No Forward Order tickets waiting</strong><p>Eligible tickets appear here automatically after Warehouse marks movement complete.</p></div></td></tr>}</tbody></table></div>
  </div>
  {selected&&<div className="card forward-entry-card"><div className="forward-form-head"><div><span className="section-kicker">CRM HANDOFF</span><h2>Forward Order Details</h2><p className="muted">Complete the forwarding references below before releasing this ticket to Warehouse Dispatch.</p></div><button className="secondary forward-close-button" type="button" onClick={()=>setSelected(null)}>Close</button></div>
   <div className="forward-ticket-summary"><div><small>Ticket Number</small><strong>{selected.ticketId}</strong></div><div><small>Customer</small><strong>{selected.customerName||'—'}</strong></div><div><small>Item Code</small><strong>{selected.itemCode||'—'}</strong></div><div className="summary-description"><small>Item Description</small><strong>{selected.itemDescription||'—'}</strong></div><div><small>Quantity</small><strong>{selected.qty??'—'}</strong></div><div><small>Destination Company</small><strong>{selected.destinationCompany||'—'}</strong></div><div><small>Original FO Number</small><strong>{selected.freightOrderNo||'—'}</strong></div></div>
   <div className="forward-form-section"><div className="forward-form-section-title"><span className="section-kicker">FORWARDING REFERENCES</span><p>Enter the CRM-generated forwarding identifiers. These values will be carried into the Dispatch stage automatically.</p></div><form className="forward-form" onSubmit={submit}><label className="system-field"><span>RPL Number <em>Required</em></span><input value={rpl} onChange={event=>setRpl(event.target.value)} placeholder="Enter RPL number" required/></label><label className="system-field"><span>FO Number (Forwarding) <em>Required</em></span><input value={forwardFo} onChange={event=>setForwardFo(event.target.value)} placeholder="Enter forwarding FO number" required/></label><label className="system-field wide-field"><span>CRM Remarks <em>Optional</em></span><textarea value={remarks} onChange={event=>setRemarks(event.target.value)} rows="4" placeholder="Add any forwarding notes, reference details or handoff remarks…"/></label><div className="forward-form-footer"><div className="next-stage"><span>Next operational stage</span><strong>Ready for Dispatch <b>→</b> Warehouse</strong></div><button className="primary forward-submit-button" disabled={saving}>{saving?'Saving Forward Order…':'Save & Send to Dispatch'}</button></div></form></div>{message&&<div className={`notice ${message.includes('successfully')?'success':''}`}>{message}</div>}</div>}
  <div className="card"><div className="card-head"><div><span className="section-kicker">FORWARDING AUDIT</span><h2>Recently Forwarded</h2><p className="muted">Completed forwarding references remain visible for CRM traceability.</p></div></div><div className="table-wrap"><table><thead><tr><th>Ticket</th><th>RPL Number</th><th>FO Number (Forwarding)</th><th>Original FO</th><th>Item Code</th><th>Completed</th><th>Status</th></tr></thead><tbody>{completed.slice(0,50).map(ticket=><tr key={ticket.id}><td><TicketLink ticket={ticket} onOpen={setDetail}/></td><td className="strong">{ticket.forwardOrder.rplNumber}</td><td className="strong">{ticket.forwardOrder.forwardingFoNumber}</td><td>{ticket.freightOrderNo||'—'}</td><td>{ticket.itemCode||'—'}</td><td>{fmt(ticket.forwardOrder.completedAt)}</td><td><span className="status-chip">{STATUS_LABELS[ticket.currentStatus]||ticket.currentStatus}</span></td></tr>)}{!completed.length&&<tr><td colSpan="7"><div className="empty-forward"><strong>No forwarding records yet</strong></div></td></tr>}</tbody></table></div></div>
  <div className="forward-audit-note"><strong>Workflow protection:</strong> Forward Order Tickets are only eligible for this desk when the ticket is inbound, destination company is 5000, and source is Haridwar, Shirwal/Shirval, Khalapur or Supplier. Other inbound tickets retain their configured workflows.</div>
  <TicketDetail ticket={detail} onClose={()=>setDetail(null)}/>
 </section>
}
