import { useState } from 'react'
import { STATUSES } from '../config.js'
import { updateTicket } from '../services.js'
import { useAuth } from '../auth.jsx'

export function BatchReinspectionRequest({ ticket, onDone }) {
  const { profile } = useAuth(); const [quantity,setQuantity]=useState(String(ticket?.qty||'')); const [remarks,setRemarks]=useState(''); const [saving,setSaving]=useState(false)
  if(!ticket)return null
  async function request(e){e.preventDefault();setSaving(true);try{const count=Number(ticket.pdi?.requestCount||0)+1;await updateTicket(ticket.id,{currentStatus:STATUSES.PENDING_WAREHOUSE,currentModule:'warehouse',previousStatus:ticket.currentStatus,pdi:{...(ticket.pdi||{}),reinspectionRequested:true,requestedQuantity:Number(quantity),requestRemarks:remarks,requestCount:count}},profile,'pdi_new_batch_requested',{module:'pdi',previousStatus:ticket.currentStatus,newStatus:STATUSES.PENDING_WAREHOUSE,details:`PDI requested new batch #${count} for reinspection. Quantity: ${quantity}.`,metadata:{requestedQuantity:Number(quantity),requestCount:count,remarks}});onDone?.()}finally{setSaving(false)}}
  return <form className="batch-request" onSubmit={request}><div className="batch-request-head"><div><div className="eyebrow">REINSPECTION REQUEST</div><h3>Request New Material Batch</h3><p className="muted">Send this ticket back to Warehouse for another batch. This remains available until PDI is completed or Warehouse confirms no stock remains.</p></div><span className="badge">Batch #{Number(ticket.pdi?.requestCount||0)+1}</span></div><div className="form-grid"><label>Quantity Requested<input type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>Reason / Remarks<textarea rows="3" value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="All material damaged. Please provide another batch for reinspection…" required/></label></div><div className="form-actions"><button className="primary" disabled={saving}>{saving?'Requesting…':'Request New Batch'}</button></div></form>
}

export function WarehouseBatchResponse({ ticket, onDone }) {
  const { profile } = useAuth(); const [quantity,setQuantity]=useState(String(ticket?.qty||'')); const [noStock,setNoStock]=useState(false); const [remarks,setRemarks]=useState(''); const [saving,setSaving]=useState(false)
  if(!ticket)return null
  async function submit(e){e.preventDefault();setSaving(true);try{const action=noStock?'warehouse_no_more_stock_available':'warehouse_new_batch_provided';await updateTicket(ticket.id,{currentStatus:STATUSES.READY_FOR_PDI,currentModule:'pdi',previousStatus:ticket.currentStatus,warehouseBatch:{...(ticket.warehouseBatch||{}),quantityProvided:noStock?0:Number(quantity),noStockAvailable:noStock,responseRemarks:remarks,batchNumber:Number(ticket.pdi?.requestCount||1)}},profile,action,{module:'warehouse',previousStatus:ticket.currentStatus,newStatus:STATUSES.READY_FOR_PDI,details:noStock?'Warehouse confirmed no more stock is available for this item.':`Warehouse provided batch #${Number(ticket.pdi?.requestCount||1)} and resent ticket to PDI. Quantity: ${quantity}.`,metadata:{quantityProvided:noStock?0:Number(quantity),noStockAvailable:noStock,batchNumber:Number(ticket.pdi?.requestCount||1),remarks}});onDone?.()}finally{setSaving(false)}}
  return <form className="batch-request" onSubmit={submit}><div className="batch-request-head"><div><div className="eyebrow">WAREHOUSE RESPONSE</div><h3>{noStock?'No Stock Available':'New Batch Allocation'}</h3><p className="muted">Respond to the PDI reinspection request. Another batch may be supplied repeatedly while stock remains.</p></div></div>{!noStock&&<label>New Batch Quantity<input type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label>}<label>Warehouse Remarks<textarea rows="3" value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="Batch details, stock position, or reason…"/></label><label className="check-row"><input type="checkbox" checked={noStock} onChange={e=>setNoStock(e.target.checked)}/> No more stock available for this item</label><div className="form-actions"><button className="primary" disabled={saving}>{saving?'Saving…':noStock?'Send No-Stock Update to PDI':'Provide Batch & Resend to PDI'}</button></div></form>
}
