import { useEffect, useMemo, useState } from 'react'
import { STATUS_LABELS, STATUSES } from '../config.js'
import { subscribeTicketActivity } from '../services.js'
import './ticket-detail-polish.css'

const excluded=new Set(['id','workflowSteps','createdBy','createdByName','createdByRole','createdAt','updatedAt','lastActionAt','lastActionBy','lastActionByName','lastActionByRole','previousStatus','statusChangedAt','dispatch','pdi','logistics','timestampTrail','forwardOrder','forwardingFoNumber'])
export function TicketLink({ticket,onOpen}){return <button type="button" className="ticket-link" onClick={()=>onOpen(ticket)}>{ticket.ticketId||ticket.id}</button>}
const tv=v=>v?.toMillis?v.toMillis():v?.toDate?v.toDate().getTime():v?new Date(v).getTime():0
const ft=v=>tv(v)?new Date(tv(v)).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'medium'}):'Not recorded yet'
const title=k=>String(k).replace(/([A-Z])/g,' $1').replace(/[_-]/g,' ').replace(/^./,c=>c.toUpperCase())
const scalar=x=>x===undefined||x===null||x===''?'—':typeof x==='boolean'?(x?'Yes':'No'):String(x)
const isTimestamp=x=>!!(x&&(x.toMillis||x.toDate))
const renderValue=x=>{if(x===undefined||x===null||x==='')return '—';if(isTimestamp(x))return ft(x);if(Array.isArray(x))return x.length?x.map((item,i)=><div className="nested-row" key={i}>{typeof item==='object'&&item!==null?<ObjectEntries value={item}/>:scalar(item)}</div>):'—';if(typeof x==='object')return <ObjectEntries value={x}/>;return scalar(x)}
function ObjectEntries({value}){return <div className="object-entries">{Object.entries(value||{}).map(([k,v])=><div className="object-entry" key={k}><small>{title(k)}</small><div>{renderValue(v)}</div></div>)}</div>}
const duration=ms=>{if(!ms)return '—';const m=Math.floor(ms/60000),h=Math.floor(m/60),d=Math.floor(h/24);return d?`${d}d ${h%24}h ${m%60}m`:h?`${h}h ${m%60}m`:`${m}m`}
const eventLabels=[['ticket_created','Ticket Created'],['warehouse_movement_completed','Warehousing Movement'],['pdi_received','Received for PDI'],['crm_forward_order_completed','Forward Order Completed'],['pdi_inspection_completed','Inspection Done'],['warehouse_new_batch_provided','New Batch Provided'],['warehouse_no_more_stock_available','No More Stock Available'],['warehouse_dispatch_completed','Dispatch Done'],['logistics_eta_submitted','Logistics Updated'],['in_transit','In Transit'],['logistics_ticket_closed','Ticket Closed'],['pdi_no_stock_ticket_closed','PDI Confirmed No Stock / Ticket Closed']]
const pdiFields=[['latestBatchNumber','Latest Batch Number'],['latestBatchQuantity','Latest Batch Quantity'],['completedAt','Completed At'],['defective','Defective'],['approved','Approved'],['totalChecked','Total Checked'],['result','Result'],['inspectorName','Inspector Name'],['reinspectionRequested','Reinspection Requested'],['latestBatchNoStock','Latest Batch No Stock'],['latestBatchNoStockRemarks','Latest Batch No Stock Remarks'],['requestRemarks','Request Remarks'],['remarks','Remarks'],['closedReason','Closed Reason'],['requestedQuantity','Requested Quantity'],['requestCount','Request Count']]
const batchFields=[['batchNumber','Batch Number'],['allocatedQty','Allocated Quantity'],['status','Status'],['requestedAt','Requested At'],['allocatedAt','Allocated At'],['completedAt','Completed At'],['noStock','No Stock'],['noStockRemarks','No Stock Remarks'],['remarks','Remarks']]
function StructuredField({label,value}){return <div className="structured-field"><small>{label}</small><strong>{renderValue(value)}</strong></div>}
function BatchTotals({totals}){const entries=Object.entries(totals||{});return <div className="batch-totals"><div className="section-mini-head"><div><span className="section-kicker">BATCH SUMMARY</span><h4>Batch Totals</h4><p className="muted">Aggregated quantities and outcomes across the complete reinspection cycle.</p></div><span className="summary-count">{entries.length} metrics</span></div><div className="totals-grid">{entries.map(([key,value])=><div className="total-metric" key={key}><span>{title(key)}</span><strong>{typeof value==='object'&&value!==null?'Details':scalar(value)}</strong>{typeof value==='object'&&value!==null&&<div className="metric-detail">{renderValue(value)}</div>}</div>)}</div></div>}
function PdiBlock({pdi}){const batches=Array.isArray(pdi?.batches)?pdi.batches:[];return <div className="pdi-block"><div className="detail-grid">{pdiFields.map(([key,label])=><StructuredField key={key} label={label} value={pdi?.[key]}/>)}</div>{batches.length>0&&<div className="batch-history"><div className="section-mini-head"><div><span className="section-kicker">REINSPECTION CYCLE</span><h4>Batch History</h4><p className="muted">Every requested, allocated and inspected batch with its warehouse outcome.</p></div><span className="summary-count">{batches.length} batch{batches.length===1?'':'es'}</span></div><div className="batch-history-list">{batches.map((batch,index)=><article className={`batch-card ${batch.noStock?'no-stock':''}`} key={batch.id||batch.batchNumber||index}><div className="batch-card-head"><div className="batch-number"><span>#{String(batch.batchNumber||index+1).padStart(2,'0')}</span><div><strong>Batch {batch.batchNumber||index+1}</strong><small>{batch.status||'Status not recorded'}</small></div></div>{batch.noStock&&<span className="badge no-stock-badge">NO STOCK</span>}</div><div className="detail-grid">{batchFields.map(([key,label])=><StructuredField key={key} label={label} value={batch?.[key]}/>)}</div></article>)}</div></div>}{pdi?.batchTotals&&<BatchTotals totals={pdi.batchTotals}/>}</div>}
function ForwardOrderBlock({forwardOrder,ticket}){if(!forwardOrder&&!ticket?.forwardingFoNumber)return null;return <div className="operational-card forward-order-detail-card"><div className="card-head"><div><span className="section-kicker">CRM FORWARD ORDER</span><h4>Forwarding References</h4><p className="muted">Original ticket references remain separate from the forwarding references added by CRM.</p></div><span className="badge">FORWARDED</span></div><div className="detail-grid"><StructuredField label="Original FO Number" value={ticket?.freightOrderNo}/><StructuredField label="RPL Number" value={forwardOrder?.rplNumber}/><StructuredField label="FO Number (Forwarding)" value={forwardOrder?.forwardingFoNumber||ticket?.forwardingFoNumber}/><StructuredField label="Forwarding Completed At" value={forwardOrder?.completedAt}/><StructuredField label="Forwarding Remarks" value={forwardOrder?.remarks}/></div></div>}
const actionTone=action=>{const a=String(action||'').toLowerCase();if(a.includes('no_stock'))return 'danger';if(a.includes('dispatch'))return 'success';if(a.includes('pdi')||a.includes('inspection'))return 'pdi';if(a.includes('batch')||a.includes('warehouse'))return 'warehouse';if(a.includes('forward'))return 'crm';if(a.includes('logistics')||a.includes('transit'))return 'logistics';return 'default'}
const actionIcon=action=>{const tone=actionTone(action);return tone==='danger'?'!':tone==='success'?'✓':tone==='pdi'?'P':tone==='warehouse'?'W':tone==='crm'?'F':tone==='logistics'?'L':'•'}
function DispatchDetails({dispatch}){return <div className="dispatch-panel"><div className="section-mini-head"><div><span className="section-kicker">FULFILMENT</span><h4>Dispatch Details</h4><p className="muted">Final warehouse dispatch information, timestamps and operational notes.</p></div><span className="dispatch-icon">↗</span></div><div className="dispatch-grid">{Object.entries(dispatch||{}).map(([key,value])=><StructuredField key={key} label={title(key)} value={value}/>)}</div></div>}
function OperationalHistory({logs}){return <div className="ops-history">{logs.length?logs.map((log,index)=><article className={`ops-event ${actionTone(log.action)}`} key={log.id||`${log.action}-${index}`}><div className="ops-rail"><span className="ops-icon">{actionIcon(log.action)}</span>{index<logs.length-1&&<span className="ops-line"/>}</div><div className="ops-body"><div className="ops-top"><span className="ops-action">{title(log.action||'Operational update')}</span><time>{ft(log.createdAt)}</time></div><strong className="ops-title">{eventLabels.find(([id])=>id===log.action)?.[1]||title(log.action||'Operational update')}</strong><p>{log.details||'No details recorded.'}</p>{(log.previousStatus||log.newStatus)&&<div className="status-transition"><span>{STATUS_LABELS[log.previousStatus]||log.previousStatus||'Start'}</span><b>→</b><span>{STATUS_LABELS[log.newStatus]||log.newStatus||'No status change'}</span></div>}</div></article>):<div className="empty-ops">No operational history recorded.</div>}</div>}
export default function TicketDetail({ticket,onClose}){const[activity,setActivity]=useState([]);useEffect(()=>subscribeTicketActivity(ticket?.id,setActivity,console.error),[ticket?.id]);const stamps=useMemo(()=>{const found={};activity.forEach(log=>{const action=log.action;if(action&&eventLabels.some(([id])=>id===action)&&!found[action])found[action]=log.createdAt;if(log.newStatus===STATUSES.READY_FOR_PDI&&!found.pdi_received)found.pdi_received=log.createdAt;if(log.newStatus===STATUSES.IN_TRANSIT&&!found.in_transit)found.in_transit=log.createdAt});if(ticket?.createdAt)found.ticket_created=found.ticket_created||ticket.createdAt;return found},[activity,ticket]);if(!ticket)return null
 const ordered=eventLabels.map(([key,label])=>({key,label,time:stamps[key]}));const created=tv(stamps.ticket_created),closed=tv(stamps.logistics_ticket_closed)||tv(stamps.pdi_no_stock_ticket_closed);const overall=created&&closed?closed-created:0;const fields=Object.entries(ticket).filter(([key])=>!excluded.has(key));const noStock=ticket.pdi?.closedReason==='no_stock'||ticket.pdi?.latestBatchNoStock===true;const operationalLogs=activity.filter(log=>log.createdAt||log.action).slice().reverse()
 return <div className="modal-backdrop" onMouseDown={onClose}><section className="ticket-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header className="ticket-detail-header"><div><div className="eyebrow">TICKET DETAIL</div><div className="ticket-title-row"><h2>{ticket.ticketId||ticket.id}</h2>{noStock&&<span className="ticket-status-alert">NO STOCK CLOSED</span>}</div><p className="muted">Created {ft(ticket.createdAt)} by {ticket.createdByName||'—'} · {ticket.createdByRole||'—'}</p></div><button className="secondary" onClick={onClose}>Close</button></header><div className="detail-summary"><div><small>Current status</small><strong>{STATUS_LABELS[ticket.currentStatus]||ticket.currentStatus||'—'}</strong></div><div><small>Current module</small><strong>{ticket.currentModule||'—'}</strong></div><div><small>Last updated</small><strong>{ft(ticket.updatedAt)}</strong></div><div><small>Last actor</small><strong>{ticket.lastActionByName||ticket.createdByName||'—'}</strong></div></div>
 <section className="ops-overview"><div className="section-mini-head"><div><span className="section-kicker">WORKFLOW MONITOR</span><h3>Important Operational Timestamps</h3><p className="muted">A visual journey of the ticket from creation through its latest operational milestone.</p></div><span className="overall-pill">{overall?duration(overall):ticket.currentStatus===STATUSES.CLOSED?'Closed':'In progress'}</span></div><div className="timestamp-board">{ordered.map((item,index)=><div className={`timestamp-card ${item.time?'done':'pending'}`} key={item.key}><span className="timestamp-index">{String(index+1).padStart(2,'0')}</span><div><small>{item.label}</small><strong>{item.time?ft(item.time):'Not recorded yet'}</strong></div>{index<ordered.length-1&&<span className="timestamp-arrow">→</span>}</div>)}</div></section>
 <h3>Workflow sequence</h3><div className="workflow-steps">{(ticket.workflowSteps||[]).map((step,index)=><span className={step===ticket.currentStatus?'workflow-step current':'workflow-step'} key={`${step}-${index}`}>{index+1}. {STATUS_LABELS[step]||step}</span>)}</div>
 <h3>Ticket information</h3><div className="detail-grid">{fields.map(([key,entry])=><StructuredField key={key} label={title(key)} value={entry}/>)}</div>
 {(ticket.dispatch||ticket.pdi||ticket.logistics||ticket.warehouseBatch||ticket.forwardOrder)&&<><div className="operational-section-heading"><div><span className="section-kicker">LIVE OPERATIONAL RECORD</span><h3>Operational Information</h3><p className="muted">Structured details from CRM, warehouse, PDI, dispatch and logistics — including forward order and no-stock closure data.</p></div>{noStock&&<span className="badge no-stock-badge">NO STOCK · CLOSED</span>}</div>{noStock&&<div className="no-stock-hero"><div className="no-stock-mark">!</div><div><strong>No Stock Closure Confirmed</strong><p>Warehouse reported no available replacement stock and PDI confirmed the ticket closure.</p><div className="no-stock-meta"><span>Reason <b>{ticket.pdi?.closedReason||'no_stock'}</b></span><span>Result <b>{ticket.pdi?.result||'NO STOCK'}</b></span><span>Inspector <b>{ticket.pdi?.inspectorName||'—'}</b></span></div></div></div>}{ticket.forwardOrder&&<ForwardOrderBlock forwardOrder={ticket.forwardOrder} ticket={ticket}/>} {ticket.pdi&&<div className="operational-card pdi-card"><div className="card-head"><div><span className="section-kicker">PDI + WAREHOUSE</span><h4>PDI / Batch Operations</h4><p className="muted">Inspection result, reinspection requests, batch history and aggregate totals.</p></div>{ticket.pdi.closedReason==='no_stock'&&<span className="badge no-stock-badge">NO STOCK</span>}</div><PdiBlock pdi={ticket.pdi}/></div>}{ticket.warehouseBatch&&<div className="operational-card"><div className="card-head"><div><span className="section-kicker">WAREHOUSE</span><h4>Warehouse Batch</h4></div></div><ObjectEntries value={ticket.warehouseBatch}/></div>}{ticket.dispatch&&<div className="operational-card"><DispatchDetails dispatch={ticket.dispatch}/></div>}{ticket.logistics&&<div className="operational-card"><div className="card-head"><div><span className="section-kicker">LOGISTICS</span><h4>Logistics Details</h4><p className="muted">ETA, transit and logistics-side operational information.</p></div></div><div className="detail-grid">{Object.entries(ticket.logistics||{}).map(([key,value])=><StructuredField key={key} label={title(key)} value={value}/>)}</div></div>}<div className="operational-card"><div className="card-head"><div><span className="section-kicker">AUDIT TRAIL</span><h4>Operational Timestamp & Operation History</h4><p className="muted">Every operational action is shown as a readable event with its exact timestamp and status transition.</p></div><span className="summary-count">{operationalLogs.length} events</span></div><OperationalHistory logs={operationalLogs}/></div></>}
 <h3>Complete activity timeline</h3><ol className="timeline">{activity.length?activity.map(log=><li key={log.id}><time>{ft(log.createdAt)}</time><strong>{log.userName||'System'} — {(log.role||log.module||'system').toUpperCase()} — {title(log.action||'activity')}</strong><span>{log.details||'No details recorded.'}</span>{(log.previousStatus||log.newStatus)&&<em>{STATUS_LABELS[log.previousStatus]||log.previousStatus||'Start'} → {STATUS_LABELS[log.newStatus]||log.newStatus||'No status change'}</em>}{log.metadata&&Object.keys(log.metadata).length>0&&<small className="timeline-meta"><ObjectEntries value={log.metadata}/></small>}</li>):<li><span>No activity records found yet.</span></li>}</ol></section></div>}
