import { useEffect, useMemo, useState } from 'react'
import { STATUS_LABELS, STATUSES } from '../config.js'
import { subscribeTicketActivity } from '../services.js'

const excluded=new Set(['id','workflowSteps','createdBy','createdByName','createdByRole','createdAt','updatedAt','lastActionAt','lastActionBy','lastActionByName','lastActionByRole','previousStatus','statusChangedAt','dispatch','pdi','logistics','timestampTrail'])
export function TicketLink({ticket,onOpen}){return <button type="button" className="ticket-link" onClick={()=>onOpen(ticket)}>{ticket.ticketId||ticket.id}</button>}
const tv=v=>v?.toMillis?v.toMillis():v?.toDate?v.toDate().getTime():v?new Date(v).getTime():0
const ft=v=>tv(v)?new Date(tv(v)).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'medium'}):'Not recorded yet'
const title=k=>String(k).replace(/([A-Z])/g,' $1').replace(/[_-]/g,' ').replace(/^./,c=>c.toUpperCase())
const scalar=x=>x===undefined||x===null||x===''?'—':typeof x==='boolean'?(x?'Yes':'No'):String(x)
const isTimestamp=x=>!!(x&&(x.toMillis||x.toDate))
const renderValue=x=>{
 if(x===undefined||x===null||x==='')return '—'
 if(isTimestamp(x))return ft(x)
 if(Array.isArray(x))return x.length?x.map((item,i)=><div key={i} style={{padding:'8px 0',borderBottom:i<x.length-1?'1px solid var(--border,#e5e7eb)':'none'}}>{typeof item==='object'&&item!==null?<ObjectEntries value={item}/>:scalar(item)}</div>):'—'
 if(typeof x==='object')return <ObjectEntries value={x}/>
 return scalar(x)
}
function ObjectEntries({value}){return <div style={{display:'grid',gap:6}}>{Object.entries(value||{}).map(([k,v])=><div key={k}><small>{title(k)}</small><div>{renderValue(v)}</div></div>)}</div>}
const duration=ms=>{if(!ms)return '—';const m=Math.floor(ms/60000),h=Math.floor(m/60),d=Math.floor(h/24);return d?`${d}d ${h%24}h ${m%60}m`:h?`${h}h ${m%60}m`:`${m}m`}
const eventLabels=[['ticket_created','Ticket Created'],['warehouse_movement_completed','Warehousing Movement'],['pdi_received','Received for PDI'],['pdi_inspection_completed','Inspection Done'],['warehouse_new_batch_provided','New Batch Provided'],['warehouse_no_more_stock_available','No More Stock Available'],['warehouse_dispatch_completed','Dispatch Done'],['logistics_eta_submitted','Logistics Updated'],['in_transit','In Transit'],['logistics_ticket_closed','Ticket Closed'],['pdi_no_stock_ticket_closed','PDI Confirmed No Stock / Ticket Closed']]
const pdiFields=[['latestBatchNumber','Latest Batch Number'],['latestBatchQuantity','Latest Batch Quantity'],['completedAt','Completed At'],['defective','Defective'],['approved','Approved'],['totalChecked','Total Checked'],['result','Result'],['inspectorName','Inspector Name'],['reinspectionRequested','Reinspection Requested'],['latestBatchNoStock','Latest Batch No Stock'],['latestBatchNoStockRemarks','Latest Batch No Stock Remarks'],['requestRemarks','Request Remarks'],['remarks','Remarks'],['closedReason','Closed Reason'],['requestedQuantity','Requested Quantity'],['requestCount','Request Count']]
const batchFields=[['batchNumber','Batch Number'],['allocatedQty','Allocated Quantity'],['status','Status'],['requestedAt','Requested At'],['allocatedAt','Allocated At'],['completedAt','Completed At'],['noStock','No Stock'],['noStockRemarks','No Stock Remarks'],['remarks','Remarks']]
function StructuredField({label,value}){return <div><small>{label}</small><strong style={{display:'block',marginTop:4,whiteSpace:'pre-wrap',wordBreak:'break-word'}}>{renderValue(value)}</strong></div>}
function PdiBlock({pdi}){const batches=Array.isArray(pdi?.batches)?pdi.batches:[];return <div style={{display:'grid',gap:16}}><div className="detail-grid">{pdiFields.map(([key,label])=><StructuredField key={key} label={label} value={pdi?.[key]}/>)}</div>{batches.length>0&&<div className="card" style={{margin:0}}><div className="card-head"><div><h4 style={{margin:0}}>Batch History</h4><p className="muted">Every requested/provided batch and its warehouse/PDI outcome.</p></div><strong>{batches.length} batch{batches.length===1?'':'es'}</strong></div><div style={{display:'grid',gap:10}}>{batches.map((batch,index)=><div key={batch.id||batch.batchNumber||index} style={{padding:14,border:'1px solid var(--border,#e5e7eb)',borderRadius:12}}><strong>Batch {batch.batchNumber||index+1}</strong><div className="detail-grid" style={{marginTop:10}}>{batchFields.map(([key,label])=><StructuredField key={key} label={label} value={batch?.[key]}/>)}</div></div>)}</div></div>}{pdi?.batchTotals&&<div className="card" style={{margin:0}}><h4 style={{marginTop:0}}>Batch Totals</h4><ObjectEntries value={pdi.batchTotals}/></div>}</div>}
export default function TicketDetail({ticket,onClose}){const[activity,setActivity]=useState([]);useEffect(()=>subscribeTicketActivity(ticket?.id,setActivity,console.error),[ticket?.id]);const stamps=useMemo(()=>{const found={};activity.forEach(log=>{const action=log.action;if(action&&eventLabels.some(([id])=>id===action)&&!found[action])found[action]=log.createdAt;if(log.newStatus===STATUSES.READY_FOR_PDI&&!found.pdi_received)found.pdi_received=log.createdAt;if(log.newStatus===STATUSES.IN_TRANSIT&&!found.in_transit)found.in_transit=log.createdAt});if(ticket?.createdAt)found.ticket_created=found.ticket_created||ticket.createdAt;return found},[activity,ticket]);if(!ticket)return null
 const ordered=eventLabels.map(([key,label])=>({key,label,time:stamps[key]}));const created=tv(stamps.ticket_created),closed=tv(stamps.logistics_ticket_closed)||tv(stamps.pdi_no_stock_ticket_closed);const overall=created&&closed?closed-created:0;const fields=Object.entries(ticket).filter(([key])=>!excluded.has(key));const noStock=ticket.pdi?.closedReason==='no_stock'||ticket.pdi?.latestBatchNoStock===true;const operationalLogs=activity.filter(log=>log.createdAt||log.action).slice().reverse()
 return <div className="modal-backdrop" onMouseDown={onClose}><section className="ticket-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="card-head"><div><div className="eyebrow">TICKET DETAIL</div><h2>{ticket.ticketId||ticket.id}</h2><p className="muted">Created {ft(ticket.createdAt)} by {ticket.createdByName||'—'} ({ticket.createdByRole||'—'})</p></div><button className="secondary" onClick={onClose}>Close</button></div><div className="detail-summary"><div><small>Current status</small><strong>{STATUS_LABELS[ticket.currentStatus]||ticket.currentStatus||'—'}</strong></div><div><small>Current module</small><strong>{ticket.currentModule||'—'}</strong></div><div><small>Last updated</small><strong>{ft(ticket.updatedAt)}</strong></div><div><small>Last actor</small><strong>{ticket.lastActionByName||ticket.createdByName||'—'}</strong></div></div>
 <h3>Important operational timestamps</h3><div className="timestamp-board">{ordered.map((item,index)=><div className={`timestamp-card ${item.time?'done':'pending'}`} key={item.key}><span className="timestamp-index">{String(index+1).padStart(2,'0')}</span><div><small>{item.label}</small><strong>{item.time?ft(item.time):'Not recorded yet'}</strong></div>{index<ordered.length-1&&<span className="timestamp-arrow">→</span>}</div>)}<div className="timestamp-total"><small>Total overall time</small><strong>{overall?duration(overall):ticket.currentStatus===STATUSES.CLOSED?'Closed timestamp not available':'In progress'}</strong><span>{closed?'Create → Closed':'Create → Current stage'}</span></div></div>
 <h3>Workflow sequence</h3><div className="workflow-steps">{(ticket.workflowSteps||[]).map((step,index)=><span className={step===ticket.currentStatus?'workflow-step current':'workflow-step'} key={`${step}-${index}`}>{index+1}. {STATUS_LABELS[step]||step}</span>)}</div>
 <h3>Ticket information</h3><div className="detail-grid">{fields.map(([key,entry])=><StructuredField key={key} label={title(key)} value={entry}/>)}</div>
 {(ticket.dispatch||ticket.pdi||ticket.logistics||ticket.warehouseBatch)&&<><h3>Operational information</h3>{noStock&&<div className="notice warning" style={{marginBottom:16}}><strong>NO STOCK CLOSURE</strong><div>Warehouse reported no stock and PDI confirmed the no-stock closure for this ticket.</div></div>}{ticket.pdi&&<div className="card" style={{margin:0,marginBottom:16}}><div className="card-head"><div><h4 style={{margin:0}}>PDI / Batch Operations</h4><p className="muted">Readable inspection, reinspection and warehouse batch information.</p></div>{ticket.pdi.closedReason==='no_stock'&&<span className="badge">NO STOCK · CLOSED</span>}</div><PdiBlock pdi={ticket.pdi}/></div>}{ticket.warehouseBatch&&<div className="card" style={{margin:0,marginBottom:16}}><h4 style={{marginTop:0}}>Warehouse Batch</h4><ObjectEntries value={ticket.warehouseBatch}/></div>}{ticket.dispatch&&<div className="card" style={{margin:0,marginBottom:16}}><h4 style={{marginTop:0}}>Dispatch</h4><ObjectEntries value={ticket.dispatch}/></div>}{ticket.logistics&&<div className="card" style={{margin:0}}><h4 style={{marginTop:0}}>Logistics</h4><ObjectEntries value={ticket.logistics}/></div>}<h4>Operational timestamp & operation history</h4><div className="timeline">{operationalLogs.length?operationalLogs.map(log=><div key={log.id} className="timeline-item" style={{padding:'12px 0',borderBottom:'1px solid var(--border,#e5e7eb)'}}><time>{ft(log.createdAt)}</time><strong style={{display:'block'}}>{title(log.action||'Operational update')}</strong><span style={{display:'block'}}>{log.details||'No details recorded.'}</span>{(log.previousStatus||log.newStatus)&&<em style={{display:'block'}}>{STATUS_LABELS[log.previousStatus]||log.previousStatus||'Start'} → {STATUS_LABELS[log.newStatus]||log.newStatus||'No status change'}</em>}</div>):<div className="muted">No operational history recorded.</div>}</div></>}
 <h3>Complete activity timeline</h3><ol className="timeline">{activity.length?activity.map(log=><li key={log.id}><time>{ft(log.createdAt)}</time><strong>{log.userName||'System'} — {(log.role||log.module||'system').toUpperCase()} — {title(log.action||'activity')}</strong><span>{log.details||'No details recorded.'}</span>{(log.previousStatus||log.newStatus)&&<em>{STATUS_LABELS[log.previousStatus]||log.previousStatus||'Start'} → {STATUS_LABELS[log.newStatus]||log.newStatus||'No status change'}</em>}{log.metadata&&Object.keys(log.metadata).length>0&&<small className="timeline-meta"><ObjectEntries value={log.metadata}/></small>}</li>):<li><span>No activity records found yet.</span></li>}</ol></section></div>}
