import { useEffect, useMemo, useState } from 'react'
import { STATUS_LABELS } from '../config.js'
import { subscribeTicketActivity } from '../services.js'

const excluded=new Set(['id','workflowSteps','createdBy','createdByName','createdByRole','createdAt','updatedAt','lastActionAt','lastActionBy','lastActionByName','lastActionByRole','previousStatus','statusChangedAt','dispatch','pdi','logistics','timestampTrail'])
export function TicketLink({ticket,onOpen}){return <button type="button" className="ticket-link" onClick={()=>onOpen(ticket)}>{ticket.ticketId||ticket.id}</button>}
const tv=v=>v?.toMillis?v.toMillis():v?new Date(v).getTime():0
const ft=v=>tv(v)?new Date(tv(v)).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'medium'}):'Awaiting timestamp'
const title=k=>k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())
const val=x=>x===undefined||x===null||x===''?'—':typeof x==='object'?Object.entries(x).map(([k,v])=>`${title(k)}: ${v??'—'}`).join(' · '):String(x)
const eventLabels=[['ticket_created','Ticket Created'],['warehouse_movement_completed','Warehousing Movement'],['pdi_received','Received for PDI'],['pdi_inspection_completed','Inspection Done'],['warehouse_new_batch_provided','New Batch Provided'],['warehouse_no_more_stock_available','No More Stock Available'],['warehouse_dispatch_completed','Dispatch Done'],['logistics_eta_submitted','Logistics Updated'],['logistics_in_transit','In Transit'],['logistics_ticket_closed','Ticket Closed']]
export default function TicketDetail({ticket,onClose}){const[activity,setActivity]=useState([]);useEffect(()=>subscribeTicketActivity(ticket?.id,setActivity,console.error),[ticket?.id]);const stamps=useMemo(()=>{const found={};activity.forEach(log=>{const key=eventLabels.find(([id])=>id===log.action)?.[0];if(key&&!found[key])found[key]=log.createdAt});if(ticket?.createdAt)found.ticket_created=found.ticket_created||ticket.createdAt;return found},[activity,ticket]);if(!ticket)return null
 const ordered=eventLabels.map(([key,label])=>({key,label,time:stamps[key]}));const created=tv(stamps.ticket_created);const closed=tv(stamps.logistics_ticket_closed);const overall=created&&closed?closed-created:0;const duration=ms=>{if(!ms)return '—';const m=Math.floor(ms/60000),h=Math.floor(m/60),d=Math.floor(h/24);return d?`${d}d ${h%24}h ${m%60}m`:h?`${h}h ${m%60}m`:`${m}m`}
 const fields=Object.entries(ticket).filter(([key])=>!excluded.has(key))
 return <div className="modal-backdrop" onMouseDown={onClose}><section className="ticket-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="card-head"><div><div className="eyebrow">TICKET DETAIL</div><h2>{ticket.ticketId||ticket.id}</h2><p className="muted">Created {ft(ticket.createdAt)} by {ticket.createdByName||'—'} ({ticket.createdByRole||'—'})</p></div><button className="secondary" onClick={onClose}>Close</button></div><div className="detail-summary"><div><small>Current status</small><strong>{STATUS_LABELS[ticket.currentStatus]||ticket.currentStatus||'—'}</strong></div><div><small>Current module</small><strong>{ticket.currentModule||'—'}</strong></div><div><small>Last updated</small><strong>{ft(ticket.updatedAt)}</strong></div><div><small>Last actor</small><strong>{ticket.lastActionByName||ticket.createdByName||'—'}</strong></div></div>
 <h3>Important operational timestamps</h3><div className="timestamp-board">{ordered.map((item,index)=><div className={`timestamp-card ${item.time?'done':'pending'}`} key={item.key}><span className="timestamp-index">{String(index+1).padStart(2,'0')}</span><div><small>{item.label}</small><strong>{item.time?ft(item.time):'Not recorded yet'}</strong></div>{index<ordered.length-1&&<span className="timestamp-arrow">→</span>}</div>)}<div className="timestamp-total"><small>Total overall time</small><strong>{overall?duration(overall):ticket.currentStatus==='closed'?'Timestamp unavailable':'Ticket still in progress'}</strong><span>{closed?'Create → Closed':'Create → Current status'}</span></div></div>
 <h3>Workflow sequence</h3><div className="workflow-steps">{(ticket.workflowSteps||[]).map((step,index)=><span className={step===ticket.currentStatus?'workflow-step current':'workflow-step'} key={`${step}-${index}`}>{index+1}. {STATUS_LABELS[step]||step}</span>)}</div><h3>Ticket information</h3><div className="detail-grid">{fields.map(([key,entry])=><div key={key}><small>{title(key)}</small><strong>{val(entry)}</strong></div>)}</div>{(ticket.dispatch||ticket.pdi||ticket.logistics||ticket.warehouseBatch)&&<><h3>Operational information</h3><div className="detail-grid">{ticket.warehouseBatch&&<div><small>Warehouse Batch</small><strong>{val(ticket.warehouseBatch)}</strong></div>}{ticket.pdi&&<div><small>PDI</small><strong>{val(ticket.pdi)}</strong></div>}{ticket.dispatch&&<div><small>Dispatch</small><strong>{val(ticket.dispatch)}</strong></div>}{ticket.logistics&&<div><small>Logistics</small><strong>{val(ticket.logistics)}</strong></div>}</div></>}
 <h3>Complete activity timeline</h3><ol className="timeline">{activity.length?activity.map(log=><li key={log.id}><time>{ft(log.createdAt)}</time><strong>{log.userName||'System'} — {(log.role||log.module||'system').toUpperCase()} — {title(log.action||'activity')}</strong><span>{log.details||'No details recorded.'}</span>{(log.previousStatus||log.newStatus)&&<em>{STATUS_LABELS[log.previousStatus]||log.previousStatus||'Start'} → {STATUS_LABELS[log.newStatus]||log.newStatus||'No status change'}</em>}{log.metadata&&Object.keys(log.metadata).length>0&&<small className="timeline-meta">{val(log.metadata)}</small>}</li>):<li><span>No activity records found yet.</span></li>}</ol></section></div>}
