import { Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import { MODULES, ROLES } from './config.js'
import { useAuth } from './auth.jsx'
import Login from './pages/Login.jsx'
import CRM from './pages/CRM.jsx'
import { Warehouse, PDI, Logistics } from './pages/Operations.jsx'
import Admin from './pages/Admin.jsx'

const modules=[[MODULES.CRM,'CRM','Add / Upload Tickets',ROLES.CRM],[MODULES.WAREHOUSE,'Warehousing','Movement & Dispatch',ROLES.WAREHOUSE],[MODULES.PDI,'PDI Inspection','Inspection Queue',ROLES.PDI],[MODULES.LOGISTICS,'Logistics','ETA & Closure',ROLES.LOGISTICS],[MODULES.ADMIN,'Admin Control Center','System Administration',ROLES.ADMIN]]
function Protected({requiredRole,children}){const{user,profile,loading}=useAuth();if(loading)return <div className="loading-screen">Loading CRM SAIDHARA…</div>;if(!user)return <Navigate to="/login" replace/>;if(!profile?.active)return <div className="loading-screen"><div className="error-box">Your account is blocked or inactive. Contact an administrator.</div></div>;if(profile.role!==ROLES.ADMIN&&profile.role!==requiredRole)return <Navigate to={`/${profile.role}`} replace/>;return children}
function Shell(){const{profile,logout,hasRole}=useAuth();const navigate=useNavigate();return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">C</span><div><strong>CRM SAIDHARA</strong><small>Operations Platform</small></div></div><nav>{modules.filter(([,,,required])=>hasRole(required)).map(([key,label,sub])=><NavLink key={key} to={`/${key}`} className={({isActive})=>isActive?'nav-item active':'nav-item'}><span>{label}</span><small>{sub}</small></NavLink>)}</nav><div className="role-card"><small>Signed in as</small><strong>{profile?.role?.toUpperCase()}</strong><span>{profile?.name||profile?.email}</span><button className="ghost" onClick={async()=>{await logout();navigate('/login')}}>Sign out</button></div></aside><main className="main"><header className="topbar"><div><span className="status-dot"/> Live Operations</div><span>{profile?.name||profile?.email}</span></header><Routes><Route path="/crm" element={<Protected requiredRole={ROLES.CRM}><CRM/></Protected>}/><Route path="/warehouse" element={<Protected requiredRole={ROLES.WAREHOUSE}><Warehouse/></Protected>}/><Route path="/pdi" element={<Protected requiredRole={ROLES.PDI}><PDI/></Protected>}/><Route path="/logistics" element={<Protected requiredRole={ROLES.LOGISTICS}><Logistics/></Protected>}/><Route path="/admin" element={<Protected requiredRole={ROLES.ADMIN}><Admin/></Protected>}/><Route path="/" element={<Navigate to={profile?.role===ROLES.ADMIN?'/admin':`/${profile?.role||ROLES.CRM}`} replace/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></main></div>}
export default function App(){const{user}=useAuth();return user?<Shell/>:<Routes><Route path="/login" element={<Login/>}/><Route path="*" element={<Navigate to="/login" replace/>}/></Routes>}
