import { addDoc, collection, doc, onSnapshot, query, serverTimestamp, where, writeBatch } from 'firebase/firestore'
import { auth, db } from './firebase.js'
import { resolveWorkflow, getInitialStatus, getNextStatus } from './workflow.js'
import { ensureInspector } from './inspectors.js'
export const TICKETS='tickets'
export const LOGS='systemLogs'
const timestampValue=value=>value?.toMillis?value.toMillis():value?new Date(value).getTime():0
const actorWithAuth=actor=>({...(actor||{}),uid:actor?.uid||auth?.currentUser?.uid||'',email:actor?.email||auth?.currentUser?.email||''})
const withTimeout=async(promise,ms,label)=>{let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`${label} is taking longer than expected. Check your Firebase connection and try again.`)),ms)})])}finally{clearTimeout(timer)}}
export async function createTicket(ticket,actor){if(!db)throw new Error('Firebase is not configured.');const safeActor=actorWithAuth(actor);if(!safeActor.uid)throw new Error('Your Firebase session is not ready. Please refresh and sign in again.');if(!ticket?.ticketType)throw new Error('Ticket type is required.');if(!ticket?.ticketId)throw new Error('Ticket ID is required.');const workflow=resolveWorkflow(ticket),initialStatus=getInitialStatus(ticket);if(!workflow.steps.length)throw new Error('No workflow is configured for this ticket. Please check the ticket type, source and destination company.');const payload={...ticket,workflowId:workflow.id,workflowSteps:workflow.steps,workflowName:workflow.ruleName,currentStatus:initialStatus,currentModule:getModuleFromStatus(initialStatus),createdBy:safeActor.uid,createdByName:safeActor.name||safeActor.email||'',createdByRole:safeActor.role||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastActionAt:serverTimestamp()};let ref;try{ref=doc(collection(db,TICKETS));await withTimeout(writeBatch(db).set(ref,payload).commit(),15000,'Ticket creation')}catch(error){console.error('Ticket creation failed:',error);if(error?.code==='permission-denied')throw new Error('Firebase denied ticket creation. Make sure this account is active and has CRM/operational access, then refresh the page.');if(error?.code==='unavailable')throw new Error('Firebase is temporarily unavailable. Check your internet connection and try again.');if(error?.code==='deadline-exceeded')throw new Error('Firebase did not respond in time. Check your internet connection and try again.');throw error instanceof Error?error:new Error('Unable to create ticket.')}try{await withTimeout(addDoc(collection(db,LOGS),buildLog({action:'ticket_created',ticketId:ref.id,module:'crm',previousStatus:'',newStatus:initialStatus,details:`${ticket.ticketType} ticket ${ticket.ticketId} created using workflow "${workflow.ruleName}". Initial status: ${initialStatus}.`,actor:safeActor,metadata:{ticketReference:ticket.ticketId,workflowId:workflow.id,workflowName:workflow.ruleName}})),10000,'Ticket audit logging')}catch(error){console.error('Ticket audit log failed after successful ticket creation:',error)}return ref.id}
export function subscribeTickets(callback,onError){if(!db)return()=>{};return onSnapshot(query(collection(db,TICKETS)),snap=>{const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>timestampValue(b.createdAt)-timestampValue(a.createdAt));callback(rows)},error=>{console.error('Ticket subscription error:',error);onError?.(error)})}
export async function updateTicket(id,changes,actor,action='ticket_updated',activity={}){if(!db)throw new Error('Firebase is not configured.');if(!id)throw new Error('Ticket ID is required.');const safeActor=actorWithAuth(actor);if(!safeActor.uid)throw new Error('Your Firebase session is not ready. Please refresh and sign in again.');if(action==='pdi_inspection_completed'&&activity?.metadata?.inspectorName)await ensureInspector(activity.metadata.inspectorName,safeActor);const batch=writeBatch(db);batch.update(doc(db,TICKETS,id),{...changes,...(changes.currentStatus?{statusChangedAt:serverTimestamp()}:{}),updatedAt:serverTimestamp(),lastActionAt:serverTimestamp(),lastActionBy:safeActor.uid,lastActionByName:safeActor.name||safeActor.email||'',lastActionByRole:safeActor.role||''});batch.set(doc(collection(db,LOGS)),buildLog({action,ticketId:id,module:activity.module||safeActor.role||'',previousStatus:activity.previousStatus??changes.previousStatus??'',newStatus:activity.newStatus??changes.currentStatus??'',details:activity.details||JSON.stringify(changes),actor:safeActor,metadata:activity.metadata||{}}));await withTimeout(batch.commit(),15000,'Ticket update')}
export async function advanceTicket(ticket,actor,extraChanges={},action='ticket_advanced'){if(!ticket?.id)throw new Error('Ticket ID is required.');const nextStatus=getNextStatus(ticket);if(!nextStatus)throw new Error('No next workflow step is available for this ticket.');const changes={...extraChanges,currentStatus:nextStatus,currentModule:getModuleFromStatus(nextStatus),previousStatus:ticket.currentStatus||'',statusChangedAt:serverTimestamp()};await updateTicket(ticket.id,changes,actor,action,{module:getModuleFromStatus(nextStatus)||actor?.role||'',previousStatus:ticket.currentStatus||'',newStatus:nextStatus,details:`Ticket advanced to ${nextStatus}.`});return nextStatus}
export async function moveTicketToStatus(ticket,status,actor,extraChanges={},action='ticket_status_changed'){if(!ticket?.id)throw new Error('Ticket ID is required.');if(!status)throw new Error('Target status is required.');if(Array.isArray(ticket.workflowSteps)&&ticket.workflowSteps.length>0&&!ticket.workflowSteps.includes(status))throw new Error('The selected status is not part of this ticket workflow.');const changes={...extraChanges,currentStatus:status,currentModule:getModuleFromStatus(status),previousStatus:ticket.currentStatus||'',statusChangedAt:serverTimestamp()};await updateTicket(ticket.id,changes,actor,action,{module:getModuleFromStatus(status)||actor?.role||'',previousStatus:ticket.currentStatus||'',newStatus:status,details:`Ticket status changed to ${status}.`})}
export function writeLog({action,ticketId='',details='',actor,module='',previousStatus='',newStatus='',metadata={}}){if(!db)return Promise.resolve();return addDoc(collection(db,LOGS),buildLog({action,ticketId,details,actor:actorWithAuth(actor),module,previousStatus,newStatus,metadata}))}
function buildLog({action,ticketId='',details='',actor,module='',previousStatus='',newStatus='',metadata={}}){const safeActor=actorWithAuth(actor);return{action,ticketId,module,previousStatus,newStatus,details,metadata,userId:safeActor.uid,userName:safeActor.name||safeActor.email||'',role:safeActor.role||'',createdAt:serverTimestamp()}}
export function subscribeTicketActivity(ticketId,callback,onError){if(!db||!ticketId)return()=>{};return onSnapshot(query(collection(db,LOGS),where('ticketId','==',ticketId)),snap=>callback(snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>timestampValue(a.createdAt)-timestampValue(b.createdAt))),onError)}
export function subscribeLogs(callback,onError){if(!db)return()=>{};return onSnapshot(query(collection(db,LOGS)),snap=>callback(snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>timestampValue(b.createdAt)-timestampValue(a.createdAt))),error=>{console.error('System log subscription error:',error);onError?.(error)})}
export function getModuleFromStatus(status){switch(status){case 'pending_warehouse':case 'ready_for_dispatch':return'warehouse';case 'ready_for_pdi':return'pdi';case 'logistics_pending':case 'in_transit':return'logistics';case 'closed':return'completed';default:return null}}
