import { addDoc, collection, doc, onSnapshot, query, serverTimestamp, where, writeBatch } from 'firebase/firestore'
import { db } from './firebase.js'
import { resolveWorkflow, getInitialStatus, getNextStatus } from './workflow.js'
import { ensureInspector } from './inspectors.js'
export const TICKETS='tickets'
export const LOGS='systemLogs'
const timestampValue=value=>value?.toMillis?value.toMillis():value?new Date(value).getTime():0
export async function createTicket(ticket,actor){if(!db)throw new Error('Firebase is not configured.');if(!ticket?.ticketType)throw new Error('Ticket type is required.');if(!ticket?.ticketId)throw new Error('Ticket ID is required.');const workflow=resolveWorkflow(ticket),initialStatus=getInitialStatus(ticket);if(!workflow.steps.length)throw new Error('No workflow is configured for this ticket. Please check the ticket type, source and destination company.');const payload={...ticket,workflowId:workflow.id,workflowSteps:workflow.steps,workflowName:workflow.ruleName,currentStatus:initialStatus,currentModule:getModuleFromStatus(initialStatus),createdBy:actor?.uid||'',createdByName:actor?.name||actor?.email||'',createdByRole:actor?.role||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastActionAt:serverTimestamp()};const ref=doc(collection(db,TICKETS)),logRef=doc(collection(db,LOGS)),batch=writeBatch(db);batch.set(ref,payload);batch.set(logRef,buildLog({action:'ticket_created',ticketId:ref.id,module:'crm',previousStatus:'',newStatus:initialStatus,details:`${ticket.ticketType} ticket ${ticket.ticketId} created using workflow "${workflow.ruleName}". Initial status: ${initialStatus}.`,actor,metadata:{ticketReference:ticket.ticketId,workflowId:workflow.id,workflowName:workflow.ruleName}}));await batch.commit();return ref.id}
// All operational portals consume the same unfiltered realtime ticket stream.
// Each module derives its queue locally from the ticket's current workflow state.
export function subscribeTickets(callback,onError){if(!db)return()=>{};return onSnapshot(query(collection(db,TICKETS)),snap=>{const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>timestampValue(b.createdAt)-timestampValue(a.createdAt));callback(rows)},error=>{console.error('Ticket subscription error:',error);onError?.(error)})}
export async function updateTicket(id,changes,actor,action='ticket_updated',activity={}){if(!db)throw new Error('Firebase is not configured.');if(!id)throw new Error('Ticket ID is required.');if(action==='pdi_inspection_completed'&&activity?.metadata?.inspectorName)await ensureInspector(activity.metadata.inspectorName,actor);const batch=writeBatch(db);batch.update(doc(db,TICKETS,id),{...changes,...(changes.currentStatus?{statusChangedAt:serverTimestamp()}:{}),updatedAt:serverTimestamp(),lastActionAt:serverTimestamp(),lastActionBy:actor?.uid||'',lastActionByName:actor?.name||actor?.email||'',lastActionByRole:actor?.role||''});batch.set(doc(collection(db,LOGS)),buildLog({action,ticketId:id,module:activity.module||actor?.role||'',previousStatus:activity.previousStatus??changes.previousStatus??'',newStatus:activity.newStatus??changes.currentStatus??'',details:activity.details||JSON.stringify(changes),actor,metadata:activity.metadata||{}}));await batch.commit()}
export async function advanceTicket(ticket,actor,extraChanges={},action='ticket_advanced'){if(!ticket?.id)throw new Error('Ticket ID is required.');const nextStatus=getNextStatus(ticket);if(!nextStatus)throw new Error('No next workflow step is available for this ticket.');const changes={...extraChanges,currentStatus:nextStatus,currentModule:getModuleFromStatus(nextStatus),previousStatus:ticket.currentStatus||'',statusChangedAt:serverTimestamp()};await updateTicket(ticket.id,changes,actor,action,{module:getModuleFromStatus(nextStatus)||actor?.role||'',previousStatus:ticket.currentStatus||'',newStatus:nextStatus,details:`Ticket advanced to ${nextStatus}.`});return nextStatus}
export async function moveTicketToStatus(ticket,status,actor,extraChanges={},action='ticket_status_changed'){if(!ticket?.id)throw new Error('Ticket ID is required.');if(!status)throw new Error('Target status is required.');if(Array.isArray(ticket.workflowSteps)&&ticket.workflowSteps.length>0&&!ticket.workflowSteps.includes(status))throw new Error('The selected status is not part of this ticket workflow.');const changes={...extraChanges,currentStatus:status,currentModule:getModuleFromStatus(status),previousStatus:ticket.currentStatus||'',statusChangedAt:serverTimestamp()};await updateTicket(ticket.id,changes,actor,action,{module:getModuleFromStatus(status)||actor?.role||'',previousStatus:ticket.currentStatus||'',newStatus:status,details:`Ticket status changed to ${status}.`})}
export async function writeLog({action,ticketId='',details='',actor,module='',previousStatus='',newStatus='',metadata={}}){if(!db)return;await addDoc(collection(db,LOGS),buildLog({action,ticketId,details,actor,module,previousStatus,newStatus,metadata}))}
function buildLog({action,ticketId='',details='',actor,module='',previousStatus='',newStatus='',metadata={}}){return{action,ticketId,module,previousStatus,newStatus,details,metadata,userId:actor?.uid||'',userName:actor?.name||actor?.email||'',role:actor?.role||'',createdAt:serverTimestamp()}}
export function subscribeTicketActivity(ticketId,callback,onError){if(!db||!ticketId)return()=>{};return onSnapshot(query(collection(db,LOGS),where('ticketId','==',ticketId)),snap=>callback(snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>timestampValue(a.createdAt)-timestampValue(b.createdAt))),onError)}
export function subscribeLogs(callback,onError){if(!db)return()=>{};return onSnapshot(query(collection(db,LOGS)),snap=>callback(snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>timestampValue(b.createdAt)-timestampValue(a.createdAt))),error=>{console.error('System log subscription error:',error);onError?.(error)})}
export function getModuleFromStatus(status){switch(status){case 'pending_warehouse':case 'ready_for_dispatch':return'warehouse';case 'ready_for_pdi':return'pdi';case 'logistics_pending':case 'in_transit':return'logistics';case 'closed':return'completed';default:return null}}
